name = "fuckit-sh" 
main = "worker.js"
compatibility_date = "2025-10-26"

[[routes]]
pattern = "fuckit.sh"
custom_domain = true

[[routes]]
pattern = "zh.fuckit.sh"
custom_domain = true

[assets]
directory = "./public"
run_worker_first = true